# Generated by Django 3.2.5 on 2021-07-12 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('star', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('vote', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('meal_name', models.CharField(max_length=255)),
                ('meal_pic', models.CharField(blank=True, max_length=255, null=True)),
                ('meal_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('meal_price', models.FloatField(blank=True, null=True)),
                ('meal_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('sn', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('shop_name', models.CharField(blank=True, max_length=20, null=True)),
                ('shop_pic', models.CharField(blank=True, max_length=255, null=True)),
                ('shop_comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'shop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('tag_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('tel', models.IntegerField()),
                ('settings', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('user_pic', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='polls.users')),
            ],
            options={
                'db_table': 'favorite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopTag',
            fields=[
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='polls.tag')),
                ('vote', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shop_tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserReference',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='polls.users')),
                ('weight', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_reference',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
